#!/usr/bin/env python3
"""Generate embed_declarations.inc and embed_map.inc from embed_manifest.txt."""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MANIFEST_FILE = os.path.join(SCRIPT_DIR, "src", "Netcode", "embed_manifest.txt")
DECL_FILE = os.path.join(SCRIPT_DIR, "src", "Netcode", "embed_declarations.inc")
MAP_FILE = os.path.join(SCRIPT_DIR, "src", "Netcode", "embed_map.inc")


def parse_manifest(path):
    entries = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("=")
            source_path = parts[0]
            target_path = parts[1] if len(parts) > 1 else parts[0]
            varname = parts[2] if len(parts) > 2 else None
            if varname is None:
                basename = os.path.basename(source_path)
                varname = os.path.splitext(basename)[0].replace(".", "_")
            entries.append((source_path, target_path, varname))
    return entries


def generate_declarations(entries, path):
    embed_root = os.path.join(SCRIPT_DIR, "src", "Netcode")
    with open(path, "w") as f:
        f.write("// Auto-generated by generate_embeds.py - do not edit manually\n\n")
        for source_path, _, varname in entries:
            embed_path = os.path.join(embed_root, source_path).replace('\\', '/')
            f.write(f"static constexpr uint8_t {varname}_nut[] = {{\n")
            f.write(f'#embed "{embed_path}"\n')
            f.write("};\n\n")
    print(f"Generated {path}")


def generate_map(entries, path):
    with open(path, "w") as f:
        f.write("// Auto-generated by generate_embeds.py - do not edit manually\n")
        for _, target_path, varname in entries:
            f.write(f'{{"{target_path}"sv, {varname}_nut}},\n')
    print(f"Generated {path}")


def main():
    decl_file = sys.argv[1] if len(sys.argv) > 1 else DECL_FILE
    map_file = sys.argv[2] if len(sys.argv) > 2 else MAP_FILE

    entries = parse_manifest(MANIFEST_FILE)
    generate_declarations(entries, decl_file)
    generate_map(entries, map_file)
    print("Done!")


if __name__ == "__main__":
    main()
