@echo off
setlocal enabledelayedexpansion

:: Switch to script directory
cd /d "%~dp0"

set MANIFEST_FILE=src\Netcode\embed_manifest.txt
set DECL_FILE=src\Netcode\embed_declarations.inc
set MAP_FILE=src\Netcode\embed_map.inc

:: Generate embed_declarations.inc
echo Generating embed_declarations.inc...
(
    echo // Auto-generated by generate_embeds.bat - do not edit manually
    echo.
    for /f "usebackq eol=# tokens=1,2,3 delims==" %%A in ("%MANIFEST_FILE%") do (
        set "VN=%%C"
        if "!VN!"=="" (
            set "VN=%%~nA"
            set "VN=!VN:.=_!"
        )
        echo static constexpr uint8_t !VN!_nut[] = {
        echo #embed "%%A"
        echo };
        echo.
    )
) > "%DECL_FILE%"

:: Generate embed_map.inc
echo Generating embed_map.inc...
(
    echo // Auto-generated by generate_embeds.bat - do not edit manually
    for /f "usebackq eol=# tokens=1,2,3 delims==" %%A in ("%MANIFEST_FILE%") do (
        set "VN=%%C"
        if "!VN!"=="" (
            set "VN=%%~nA"
            set "VN=!VN:.=_!"
        )
        echo {"%%B"sv, !VN!_nut},
    )
) > "%MAP_FILE%"

echo Done!
