<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishDir>publish</PublishDir>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
      <Compile Include="src/TCP.fs" />
      <Compile Include="src/UDP.fs" />  
      <Compile Include="src/BOT.fs" />
      <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
